name: KanalD Daily M3U Update

on:
  schedule:
    # Her gün Türkiye saatiyle sabah 09:00'da (UTC 06:00) çalışır.
    # Saati kendinize göre ayarlayabilirsiniz.
    - cron: "0 6 * * *"
  # Manuel olarak çalıştırma imkanı için
  workflow_dispatch:

permissions:
  # Repoya kod gönderebilmek (commit/push) için bu izin gerekli
  contents: write

concurrency:
  # Aynı anda sadece bir tane "kanald-m3u" işinin çalışmasını sağlar
  group: kanald-m3u
  cancel-in-progress: true

jobs:
  run-kanald-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 360   # İşlem en fazla 6 saat sürebilir

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4
        with:
          # Commit atacak bot'un kimlik bilgilerini kalıcı hale getir
          persist-credentials: true

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          # Pip bağımlılıklarını cache'leyerek kurulumu hızlandır
          cache: "pip"
          cache-dependency-path: "KanalD/requirements.txt"

      - name: 3. Install Dependencies
        run: pip install -r KanalD/requirements.txt

      - name: 4. Run KanalD Scraper Script
        # Script'in bulunduğu klasörde çalıştırarak çıktıların doğru yere gelmesini sağla
        run: python KanalD/kanald_scraper.py
        working-directory: KanalD

      - name: 5. Commit and Push Changes
        run: |
          set -e # Herhangi bir komut hata verirse işlemi durdur
          
          # Git için bot kimliğini ayarla
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Oluşturulan dosyaları git'e ekle. Dosya yoksa hata vermemesi için "|| true"
          git add KanalD/KanalD.m3u KanalD/programlar/*.m3u || true
          
          # Eğer eklenecek bir değişiklik yoksa, script'i başarıyla sonlandır
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          # Değişiklik varsa commit at
          # [skip ci] ifadesi, bu commit'in tekrar bir Actions workflow'u tetiklemesini engeller
          git commit -m "Update KanalD M3U files [skip ci]"
          
          # Değişiklikleri ana dala (main/master) gönder
          git push
