name: KanalD Daily M3U Update

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: kanald-m3u
  cancel-in-progress: true

jobs:
  run-kanald-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    # !! DÜZELTME: Tüm iş için varsayılan çalışma dizinini burada belirtiyoruz.
    defaults:
      run:
        working-directory: ./KanalD

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          # Cache yolu artık ana dizine göre doğru
          cache-dependency-path: "KanalD/requirements.txt"

      - name: 3. Install Dependencies
        # Bu adım artık otomatik olarak ./KanalD içinde çalışacak
        run: pip install -r requirements.txt

      - name: 4. Run KanalD Scraper Script
        # Artık sadece dosya adını vermemiz yeterli
        run: python kanald_scraper.py

      - name: 5. Commit and Push Changes
        # Bu adım da otomatik olarak ./KanalD içinde çalışacak
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Dosya yolları artık daha basit
          git add KanalD.m3u programlar/*.m3u || true
          
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Update KanalD M3U files [skip ci]"
          git push